SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

DEBUG = True

TICK_RATE = 60

DISPLAY_CAPTION = "Labirint"

# BLADE
BLADE_BASE_POWER = 3
BLADE_POWER_BAFF = 2
BLADE_VENOM_BAFF = 2

# ENTITY
PLAYER_BASE_HP = 6
PLAYER_BASE_SPEED = 3
PLAYER_WALK_ANIMATION = [f"sprites/player/walk/Player ({x}).png" for x in range(1, 9)]  # 8 кадров
PLAYER_IDLE_ANIMATION = [f"sprites/player/idle/Player ({x}).png" for x in range(1, 5)]  # 4 кадра

WEAK_ENEMY_BASE_HP = 1
WEAK_ENEMY_BASE_SPEED = 1
WEAK_ENEMY_BASE_POWER = 1

NORMAL_ENEMY_BASE_HP = 1
NORMAL_ENEMY_BASE_SPEED = 1
NORMAL_ENEMY_BASE_POWER = 1

STRONG_ENEMY_BASE_SPEED = 3
STRONG_ENEMY_BASE_POWER = 3
